--- #YAML:1.0
name:               Astro-Hipparcos
version:            0.05
abstract:           Perl extension for reading the Hipparcos star catalog
author:
    - Steffen Mueller <smueller@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    ExtUtils::XSpp:  0.05
no_index:
    directory:
        - t
        - inc
        - buildtools
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
